// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_ProjectAP3

/*
#include "../ui.h"

void ui_APFace_screen_init(void)
{
ui_APFace = lv_obj_create(NULL);
lv_obj_clear_flag( ui_APFace, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_APFace, lv_color_hex(0x2A0A03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_APFace, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_toggle = lv_switch_create(ui_APFace);
lv_obj_set_width( ui_toggle, 80);
lv_obj_set_height( ui_toggle, 40);
lv_obj_set_x( ui_toggle, 0 );
lv_obj_set_y( ui_toggle, 25 );
lv_obj_set_align( ui_toggle, LV_ALIGN_CENTER );
lv_obj_add_state( ui_toggle, LV_STATE_CHECKED );     /// States
lv_obj_set_style_bg_color(ui_toggle, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_toggle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_toggle, lv_color_hex(0x458A8A), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_toggle, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_CTSlabel = lv_textarea_create(ui_APFace);
lv_obj_set_width( ui_CTSlabel, 105);
lv_obj_set_height( ui_CTSlabel, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_CTSlabel, 0 );
lv_obj_set_y( ui_CTSlabel, -48 );
lv_obj_set_align( ui_CTSlabel, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_CTSlabel,"Course");
lv_obj_clear_flag( ui_CTSlabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_CTSlabel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_CTSlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CTSlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CTSlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CTSlabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CTSlabel, lv_color_hex(0x2A0A03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CTSlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CTSlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CTSlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CTSlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CTSlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CTSlabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_CTSfield = lv_textarea_create(ui_APFace);
lv_obj_set_width( ui_CTSfield, 91);
lv_obj_set_height( ui_CTSfield, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_CTSfield, 0 );
lv_obj_set_y( ui_CTSfield, -20 );
lv_obj_set_align( ui_CTSfield, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_CTSlabel, heading_to_steer);
lv_textarea_set_placeholder_text(ui_CTSfield,"---");
lv_obj_clear_flag( ui_CTSfield, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_CTSfield, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_CTSfield, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CTSfield, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CTSfield, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CTSfield, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CTSfield, lv_color_hex(0x2A0A03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CTSfield, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CTSfield, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CTSfield, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CTSfield, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CTSfield, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CTSfield, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_down10 = lv_btn_create(ui_APFace);
lv_obj_set_width( ui_down10, 80);
lv_obj_set_height( ui_down10, 40);
lv_obj_set_x( ui_down10, -75 );
lv_obj_set_y( ui_down10, 94 );
lv_obj_set_align( ui_down10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_down10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_down10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_down10, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_down10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_down10, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_down10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_down10, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_down10, lv_color_hex(0x458A8A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_down10, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1 = lv_label_create(ui_down10);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -2 );
lv_obj_set_y( ui_Label1, -1 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"<<");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_down1 = lv_btn_create(ui_APFace);
lv_obj_set_width( ui_down1, 80);
lv_obj_set_height( ui_down1, 40);
lv_obj_set_x( ui_down1, -75 );
lv_obj_set_y( ui_down1, -94 );
lv_obj_set_align( ui_down1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_down1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_down1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_down1, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_down1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_down1, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_down1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_down1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_down1, lv_color_hex(0x458A8A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_down1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label2 = lv_label_create(ui_down1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -2 );
lv_obj_set_y( ui_Label2, -1 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"<");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_up1 = lv_btn_create(ui_APFace);
lv_obj_set_width( ui_up1, 80);
lv_obj_set_height( ui_up1, 40);
lv_obj_set_x( ui_up1, 75 );
lv_obj_set_y( ui_up1, -94 );
lv_obj_set_align( ui_up1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_up1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_up1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_up1, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_up1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_up1, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_up1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_up1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_up1, lv_color_hex(0x458A8A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_up1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label3 = lv_label_create(ui_up1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -2 );
lv_obj_set_y( ui_Label3, -1 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,">");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_up10 = lv_btn_create(ui_APFace);
lv_obj_set_width( ui_up10, 80);
lv_obj_set_height( ui_up10, 40);
lv_obj_set_x( ui_up10, 75 );
lv_obj_set_y( ui_up10, 94 );
lv_obj_set_align( ui_up10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_up10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_up10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_up10, lv_color_hex(0x383838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_up10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_up10, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_up10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_up10, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_up10, lv_color_hex(0x458A8A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_up10, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label4 = lv_label_create(ui_up10);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -2 );
lv_obj_set_y( ui_Label4, -1 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,">>");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_toggle, ui_event_toggle, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_down10, ui_event_down10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_down1, ui_event_down1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_up1, ui_event_up1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_up10, ui_event_up10, LV_EVENT_ALL, NULL);

}


*/