// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_ProjectAP3


/*
#include "ui.h"
#include "ui_helpers.h"


void callautopilot(lv_obj_t *parent)

{
///////////////////// VARIABLES ////////////////////

 // send initial ESP-NOW handshake
        requestHTS = 1;
        APbutton = "requestHTS";
        APCommand.doit = APbutton;
esp_err_t result = esp_now_send(broadcastAddress, (uint8_t *) &APCommand, sizeof(APCommand));
requestHTS = 0;
autopilot_main_update_label()


// SCREEN: ui_APFace
void ui_APFace_screen_init(void);
lv_obj_t *ui_APFace;
void ui_event_toggle( lv_event_t * e);
lv_obj_t *ui_toggle;
lv_obj_t *ui_CTSlabel;
lv_obj_t *ui_CTSfield;
void ui_event_down10( lv_event_t * e);
lv_obj_t *ui_down10;
lv_obj_t *ui_Label1;
void ui_event_down1( lv_event_t * e);
lv_obj_t *ui_down1;
lv_obj_t *ui_Label2;
void ui_event_up1( lv_event_t * e);
lv_obj_t *ui_up1;
lv_obj_t *ui_Label3;
void ui_event_up10( lv_event_t * e);
lv_obj_t *ui_up10;
lv_obj_t *ui_Label4;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_toggle( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      ToggleON( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      ToggleOFF( e );
}
}
void ui_event_down10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      down10button( e );
}
}
void ui_event_down1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      down1button( e );
}
}
void ui_event_up1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      up1button( e );
}
}
void ui_event_up10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      up10button( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_APFace_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_APFace);
}


}

*/