// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_ProjectAP3

#ifndef _SQUARELINE_PROJECTAP3_UI_H
#define _SQUARELINE_PROJECTAP3_UI_H

#ifdef __cplusplus
extern "C" {
#endif


    #include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"


/*
// SCREEN: ui_APFace
void ui_APFace_screen_init(void);
extern lv_obj_t *ui_APFace;
void ui_event_toggle( lv_event_t * e);
extern lv_obj_t *ui_toggle;
extern lv_obj_t *ui_CTSlabel;
extern lv_obj_t *ui_CTSfield;
void ui_event_down10( lv_event_t * e);
extern lv_obj_t *ui_down10;
extern lv_obj_t *ui_Label1;
void ui_event_down1( lv_event_t * e);
extern lv_obj_t *ui_down1;
extern lv_obj_t *ui_Label2;
void ui_event_up1( lv_event_t * e);
extern lv_obj_t *ui_up1;
extern lv_obj_t *ui_Label3;
void ui_event_up10( lv_event_t * e);
extern lv_obj_t *ui_up10;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui____initial_actions0;

*/


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
