// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_ProjectAP3


/*
#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ToggleON(lv_event_t * e);
void ToggleOFF(lv_event_t * e);
void down10button(lv_event_t * e);
void down1button(lv_event_t * e);
void up1button(lv_event_t * e);
void up10button(lv_event_t * e);

#ifdef __cplusplus
} //extern "C"
#endif

#endif
*/