// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_ProjectAP3


/*
#include "ui.h"

void ToggleON(lv_event_t * e)
{
        APbutton = "toggleAP";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();
}

void ToggleOFF(lv_event_t * e)
{
        APbutton = "toggleAP";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();

}

void down10button(lv_event_t * e)
{
           APbutton = "downten";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();

   }

void down1button(lv_event_t * e)
{
        APbutton = "downone";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();
}

void up1button(lv_event_t * e)
{
        APbutton = "upone";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();
}

void up10button(lv_event_t * e)
{
        APbutton = "upten";
        APCommand.doit = APbutton;
         
        // Send message via ESP-NOW
        autopilot_wifi_event();
}

*/